### ISSUE TITLE
project dead

### ISSUE THREAD

**Issue by 0x131315** [cfryanr/hikvision-download-assistant#7]
alive project: https://github.com/phillmac/hikvision-download-assistant

**Comment by cfryanr** [comment]
To be clear, I (the original author of this project) do not know or have any affiliation with the person who posted the above comment. Anyone using their fork of my project should do so at their own risk.

In terms of this project being dead... this was a weekend project that I posted in case anyone else might find it useful. I have not spent time to maintain it. Your milage may vary.

**Comment by 0x131315** [comment]
Your code is just outdated and does not work. Pullrequests with fixes for 3 years not accepted. And there are living forks in which problems are solved that are supported.

**Comment by cfryanr** [comment]
I am happy to see the code live on in forks. That's why I open sourced this project in the first place.

I'm only pointing out that I have no affiliation with any fork of this project and therefore cannot endorse any particular fork as a replacement. Users should make their own choices about which one to use, if any.

**Comment by 0x131315** [comment]
ok
It's just not obvious that the project is not developing. I also wanted to make a pull request, but I saw that no one accepts them
Thanks for code and comments
